version: '2'
services:
  grafana:
    image: docbuc/grafana:3-compose
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=geheim
  telegraf:
    image: docbuc/telegraf:3-compose
    build: telegraf/
    restart: always
  influx:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=iijineeZ9iet
      - INFLUXDB_DB=telegraf

