version: '3.4'
services:
  mongo1:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol1:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
  mongo2:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol2:/data/db
    deploy:
      placement:
        constraints: [node.hostname == worker1]
  mongo3:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol3:/data/db
    deploy:
      placement:
        constraints: [node.hostname == worker2]
  api:
    restart: always
    build: api
    image: docbuc/mwaapi:3.1
    environment:
      # - MONGO_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      - MONGO_URL=mongodb://mongo1:27017/
    depends_on:
      - mongo1
    ports:
      - 3000:3000
  redis:
    image: redis:6-alpine
  frontend:
    restart: always
    build: frontend
    image: docbuc/mwafe:3.1
    depends_on:
      - api
    ports:
      - 8080:8080
      - 80:80
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  mongovol1:
  mongovol2:
  mongovol3:

