version: '3'
services:
  db:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ciel5eeNgeez
      - MYSQL_PASSWORD=IeMaovahM2ba
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud:fpm
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=IeMaovahM2ba
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  web:
    image: nginx:1
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
    restart: unless-stopped
volumes:
  db:
  nextcloud:
  nextcloud_data:

